function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    params(7)=(1+params(8))*(1+params(9));
    params(4)=params(10)/params(11)-params(9)-params(8)-params(8)*params(9);
    params(1)=params(7)/(params(5)/params(11)+1-params(4));
    l_ss=0.33;
    k_ss=l_ss*((params(7)*1/params(1)-(1-params(4)))/params(5))^(1/(params(5)-1));
    i_ss=k_ss*(params(8)*params(9)+params(4)+params(8)+params(9));
    y_ss=k_ss^params(5)*l_ss^(1-params(5));
    c_ss=y_ss-i_ss;
    params(2)=(1-params(5))*(k_ss/l_ss)^params(5)*(1-l_ss)/c_ss^params(3);
    ys_(8)=log(i_ss);
    ys_(7)=log((1-params(5))*y_ss/l_ss);
    ys_(6)=y_ss*params(5)*4/k_ss;
    ys_(1)=log(y_ss);
    ys_(3)=log(k_ss);
    ys_(2)=log(c_ss);
    ys_(4)=log(l_ss);
    ys_(5)=0;
    % Auxiliary equations
ys_(9)=exo_(1);
ys_(10)=exo_(1);
ys_(11)=exo_(1);
ys_(12)=exo_(1);
ys_(13)=exo_(1);
ys_(14)=exo_(1);
ys_(15)=exo_(1);
ys_(16)=exo_(1);
end
