"""Faithfulness tests for the asset-pricing tutorial.

These tests pin the single finding in
``bullshit-detector_asset-pricing_2026-05-20.md``:

- Finding 1 (DATA DRIFT): the convergence statistics (iteration count,
  sup-norm residual, central max relative error) were embedded into the
  README prose by f-strings and were not persisted to any committed
  artifact, so they could not be cross-checked without a re-run. The honest
  fix emits ``tables/convergence.csv`` carrying those three quantities, and
  the README convergence claims must match that CSV.

The README and ``tables/`` CSVs are generated artifacts regenerated by
``python run.py``. The violated-invariant test encodes the buggy property
(no convergence CSV) and FAILS once the fix is applied; the honest-fix tests
PASS.
"""
import re
from pathlib import Path

import pandas as pd

TUTORIAL_DIR = Path(__file__).resolve().parents[1]
README = (TUTORIAL_DIR / "README.md").read_text()
TABLES_DIR = TUTORIAL_DIR / "tables"
CONVERGENCE_CSV = TABLES_DIR / "convergence.csv"


# ---------------------------------------------------------------------------
# Finding 1: convergence statistics must be persisted to a CSV artifact.
# ---------------------------------------------------------------------------
def test_finding1_violated_invariant_no_convergence_csv():
    """Violated invariant: no committed artifact holds the convergence stats.

    The buggy tutorial only emitted price-dividend-ratio.csv, with no solver
    diagnostics. This test passes on the buggy repo and FAILS once
    tables/convergence.csv is added.
    """
    assert not CONVERGENCE_CSV.exists()


def test_finding1_honest_fix_convergence_csv_exists():
    """Honest-fix: tables/convergence.csv carries the three convergence stats."""
    assert CONVERGENCE_CSV.exists()
    quantities = list(pd.read_csv(CONVERGENCE_CSV)["Quantity"])
    assert any("iterations" in q.lower() for q in quantities)
    assert any("residual" in q.lower() for q in quantities)
    assert any("relative error" in q.lower() for q in quantities)


def test_finding1_readme_iterations_match_csv():
    """The README iteration count matches the persisted CSV value."""
    df = pd.read_csv(CONVERGENCE_CSV)
    iterations = int(
        df.loc[df.Quantity == "Baseline iterations", "Value"].iloc[0]
    )
    m = re.search(r"converges in\s*\*\*(\d+) iterations\*\*", README)
    assert m is not None, "README iteration claim not found"
    assert int(m.group(1)) == iterations
