"""Faithfulness tests for the consumption-savings tutorial.

These tests pin the three findings in
``bullshit-detector_consumption-savings_2026-05-20.md``:

- Finding 1 (MISLABELED): the reported "MPC" was ``dc*/da`` (gradient of the
  consumption policy w.r.t. assets), not the marginal propensity to consume
  out of cash-on-hand ``dc*/dw`` with ``w = R a + z``. Since ``dw/da = R``,
  the honest quantity is ``(dc*/da) / R``. The fix divides the gradient by
  the gross return before reporting.
- Finding 2 (DILUTED): the Solution Method pseudocode showed only the
  cash-on-hand upper bound in the feasibility set, while the comment claimed
  "respects no-borrowing". The honest fix adds the ``0 <= g_l`` lower bound
  to the pseudocode feasibility line.
- Finding 3 (DATA DRIFT): convergence statistics, MPCs, and simulated
  quantiles were embedded into the README from runtime with no committed
  artifact to cross-check. The honest fix emits ``tables/key-scalars.csv``.

The README and ``tables/`` CSVs are generated artifacts regenerated by
``python run.py``. ``run.py`` only executes ``main()`` under ``__main__``,
so its helper functions are imported directly. The violated-invariant tests
encode each buggy property and FAIL once the fix is applied; the honest-fix
tests PASS.
"""
import importlib.util
import re
from pathlib import Path

import numpy as np
import pandas as pd

TUTORIAL_DIR = Path(__file__).resolve().parents[1]
README = (TUTORIAL_DIR / "README.md").read_text()
RUN_PY = (TUTORIAL_DIR / "run.py").read_text()
KEY_SCALARS_CSV = TUTORIAL_DIR / "tables" / "key-scalars.csv"


def _load_run_module():
    """Import run.py without executing main() (guarded by __main__)."""
    spec = importlib.util.spec_from_file_location(
        "cs_run", TUTORIAL_DIR / "run.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# ---------------------------------------------------------------------------
# Finding 1: MPC must be dc*/dw = (dc*/da)/R, not dc*/da.
# ---------------------------------------------------------------------------
def _main_grid_solution():
    """Solve on the same grids run.py uses, so MPC values are comparable."""
    mod = _load_run_module()
    from lib.discretize import rouwenhorst
    from lib.grids import exponential_grid

    beta, r, sigma_crra = 0.95, 0.03, 2.0
    z_log, trans, _ = rouwenhorst(n=5, mu=0.0, sigma=0.1, rho=0.9)
    z_grid = np.exp(np.asarray(z_log, dtype=float).flatten())
    transition = np.asarray(trans, dtype=float)
    a_grid = np.asarray(exponential_grid(0.0, 20.0, 300, density=3.0), dtype=float)
    a_choice = np.asarray(exponential_grid(0.0, 20.0, 900, density=3.0), dtype=float)
    sol = mod.solve_income_fluctuation(
        a_grid, a_choice, z_grid, transition, beta, r, sigma_crra,
        tol=1e-6, max_iter=2000, label="test",
    )
    return sol, a_grid, 1.0 + r


def test_finding1_violated_invariant_dc_da_differs_from_mpc():
    """Violated invariant: dc*/da differs from the true MPC dc*/dw by R.

    The buggy code reported dc*/da. This test encodes that the two genuinely
    differ, so reporting dc*/da is not reporting the MPC.
    """
    sol, a_grid, gross_return = _main_grid_solution()
    policy_c = np.asarray(sol["policy_c"])
    dc_da = np.gradient(policy_c[:, 2], a_grid)[5:20]
    assert not np.allclose(dc_da, dc_da / gross_return, rtol=1e-6)


def test_finding1_honest_fix_reported_mpc_is_dc_dw():
    """Honest-fix: the reported near-zero MPC equals (dc*/da)/R."""
    sol, a_grid, gross_return = _main_grid_solution()
    policy_c = np.asarray(sol["policy_c"])
    expected_mpc = float(
        np.mean(np.gradient(policy_c[:, 2], a_grid)[5:20] / gross_return)
    )
    df = pd.read_csv(KEY_SCALARS_CSV)
    reported = float(
        df.loc[df.Quantity == "MPC near zero assets (median z)", "Value"].iloc[0]
    )
    assert np.isclose(reported, expected_mpc, rtol=0.02)


def test_finding1_run_py_divides_gradient_by_gross_return():
    """Honest-fix: run.py computes the MPC as (dc/da)/gross_return."""
    assert "dc_da_mid / gross_return" in RUN_PY


# ---------------------------------------------------------------------------
# Finding 2: pseudocode feasibility must show the no-borrowing lower bound.
# ---------------------------------------------------------------------------
def test_finding2_violated_invariant_pseudocode_omits_lower_bound():
    """Violated invariant: pseudocode feasibility shows only the upper bound.

    The buggy pseudocode had ``feasible(g_l) := { g_l <= R a_i + z_j }``.
    This test encodes that buggy line and FAILS once the lower bound is added.
    """
    assert "feasible(g_l) := { g_l <= R a_i + z_j }" in RUN_PY


def test_finding2_honest_fix_pseudocode_shows_lower_bound():
    """Honest-fix: the pseudocode feasibility set includes 0 <= g_l."""
    m = re.search(r"feasible\(g_l\) := \{ ([^}]+) \}", README)
    assert m is not None, "feasibility pseudocode line not found in README"
    feasibility = m.group(1)
    assert "0 <= g_l" in feasibility
    assert "g_l <= R a_i + z_j" in feasibility


# ---------------------------------------------------------------------------
# Finding 3: runtime numbers must be persisted to a CSV artifact.
# ---------------------------------------------------------------------------
def test_finding3_violated_invariant_no_scalars_csv():
    """Violated invariant: no committed artifact holds the runtime scalars.

    The buggy tutorial wrote no tables CSV. This test passes on the buggy
    repo and FAILS once tables/key-scalars.csv is added.
    """
    assert not KEY_SCALARS_CSV.exists()


def test_finding3_honest_fix_scalars_csv_exists():
    """Honest-fix: tables/key-scalars.csv carries the runtime scalars."""
    assert KEY_SCALARS_CSV.exists()
    quantities = list(pd.read_csv(KEY_SCALARS_CSV)["Quantity"])
    assert any("iterations" in q.lower() for q in quantities)
    assert any("MPC near zero" in q for q in quantities)
    assert any("median wealth" in q.lower() for q in quantities)


def test_finding3_readme_iterations_match_csv():
    """The README iteration count matches the persisted CSV value."""
    df = pd.read_csv(KEY_SCALARS_CSV)
    iterations = int(
        df.loc[df.Quantity == "Main-grid VFI iterations", "Value"].iloc[0]
    )
    m = re.search(r"converges in\s*\*\*(\d+) iterations\*\*", README)
    assert m is not None, "README iteration claim not found"
    assert int(m.group(1)) == iterations
