"""Faithfulness tests for the aiyagari tutorial.

These tests pin the two findings in
``bullshit-detector_aiyagari_2026-05-20.md``:

- Finding 1 (DATA DRIFT): the README equilibrium equation asserted
  ``K^s(r*) = ... = K^d(r*)`` (exact equality), but ``K_eq`` is taken from
  the demand side while ``mean_wealth`` is the supply side, and the
  diagnostics table reports both as distinct values that differ by the
  bisection tolerance residual. The honest fix states the relation as
  approximate (``K^s(r*) \\approx K^d(r*)``) and notes the residual.
- Finding 2 (DATA DRIFT): the bisection step count and final VFI iteration
  count were injected into the README prose from runtime variables and were
  not persisted to any committed artifact. The honest fix adds both as rows
  of ``tables/equilibrium.csv``.

The README and ``tables/equilibrium.csv`` are treated as generated artifacts;
they are regenerated by ``python run.py``. The violated-invariant tests
encode the buggy property and must FAIL once the fix is applied and the
artifacts are regenerated; the honest-fix tests must PASS.
"""
from pathlib import Path

import pandas as pd

TUTORIAL_DIR = Path(__file__).resolve().parents[1]
README = (TUTORIAL_DIR / "README.md").read_text()
EQUILIBRIUM_CSV = TUTORIAL_DIR / "tables" / "equilibrium.csv"


# ---------------------------------------------------------------------------
# Finding 1: equilibrium equation states exact equality vs. approximate.
# ---------------------------------------------------------------------------
def test_finding1_violated_invariant_equation_states_exact_equality():
    """Violated invariant: README asserts K^s = ... = K^d exactly.

    The buggy README chained the supply sum and demand into one equality.
    This test encodes the buggy property: it passes on the buggy README and
    FAILS once the equation is restated as approximate.
    """
    assert r"\,\mu(a_i,z_j) = K^d(r^{\ast})" in README


def test_finding1_honest_fix_equation_is_approximate():
    """Honest-fix: README states K^s(r*) approx K^d(r*) and flags the residual."""
    assert r"K^s(r^{\ast}) \approx K^d(r^{\ast})" in README
    assert "tolerance" in README


def test_finding1_table_reports_both_sides_distinctly():
    """The diagnostics table still reports demand-side K* and supply-side E[a]."""
    df = pd.read_csv(EQUILIBRIUM_CSV)
    k_star = float(df.loc[df.Variable == "Aggregate capital $K^{\\ast}$", "Value"].iloc[0])
    e_a = float(df.loc[df.Variable == "Mean wealth $\\mathbb{E}[a]$", "Value"].iloc[0])
    # They differ by the tolerance residual; the prose now says so.
    assert abs(k_star - e_a) > 1e-4


# ---------------------------------------------------------------------------
# Finding 2: bisection and VFI counts must be persisted to the CSV artifact.
# ---------------------------------------------------------------------------
def _csv_variables():
    return list(pd.read_csv(EQUILIBRIUM_CSV)["Variable"])


def test_finding2_violated_invariant_counts_absent_from_csv():
    """Violated invariant: step counts not persisted to the CSV artifact.

    The buggy run.py emitted bisection and VFI counts only into README prose.
    This fails once both rows are added to tables/equilibrium.csv.
    """
    variables = _csv_variables()
    assert not any("Bisection steps" in v for v in variables)
    assert not any("VFI iterations" in v for v in variables)


def test_finding2_honest_fix_counts_persisted_to_csv():
    """Honest-fix: bisection step count and VFI iteration count are CSV rows."""
    variables = _csv_variables()
    assert any("Bisection steps" in v for v in variables)
    assert any("VFI iterations" in v for v in variables)


def test_finding2_readme_counts_match_csv():
    """The README step counts match the persisted CSV values."""
    df = pd.read_csv(EQUILIBRIUM_CSV)
    bisection = int(df.loc[df.Variable == "Bisection steps", "Value"].iloc[0])
    vfi = int(df.loc[df.Variable == "VFI iterations", "Value"].iloc[0])
    assert f"**{bisection}** bisection steps" in README
    assert f"**{vfi}** iterations" in README
