"""Faithfulness tests for the diamond-mortensen-pissarides tutorial.

These tests pin the two findings in
``bullshit-detector_diamond-mortensen-pissarides_2026-05-20.md``:

- Finding 1 (DILUTED): the README stated the nonlinear free-entry operator is
  a contraction "with modulus beta*(1-sigma)=0.9621". That is only the
  modulus of the linear term; substituting theta(E[J']) inside the Bellman
  adds a negative correction that tightens the effective modulus to about
  0.29. A reader using 0.9621 would predict ~654 iterations to tol=1e-11,
  inconsistent with the ~26 the solver actually takes. The honest fix states
  the effective modulus and reconciles it with the observed iteration count.
- Finding 2 (DATA DRIFT): the policy gap, grid gap, and iteration counts were
  injected into README prose with no committed artifact to cross-check. The
  honest fix emits ``tables/solver-diagnostics.csv``.

The README and ``tables/`` CSVs are generated artifacts regenerated by
``python run.py``. The violated-invariant tests encode each buggy property
and FAIL once the fix is applied; the honest-fix tests PASS.
"""
import math
import re
from pathlib import Path

import pandas as pd

TUTORIAL_DIR = Path(__file__).resolve().parents[1]
README = (TUTORIAL_DIR / "README.md").read_text()
DIAGNOSTICS_CSV = TUTORIAL_DIR / "tables" / "solver-diagnostics.csv"


# ---------------------------------------------------------------------------
# Finding 1: the stated contraction modulus must be the effective modulus.
# ---------------------------------------------------------------------------
def test_finding1_violated_invariant_modulus_is_linear_term_only():
    """Violated invariant: README states the contraction modulus as
    beta*(1-sigma)=0.9621.

    This test encodes the buggy claim and FAILS once the prose is corrected
    to state the effective modulus.
    """
    assert "contraction with modulus $\\beta(1-\\sigma)=0.9621$" in README


def test_finding1_stated_modulus_inconsistent_with_iteration_count():
    """The linear-term modulus 0.9621 cannot explain the observed iterations.

    Reaching tol=1e-11 from an order-1 initial error at modulus 0.9621 needs
    roughly 654 iterations; the solver terminates far sooner, which only the
    tighter effective modulus (~0.29) explains.
    """
    iters_needed_linear = math.ceil(-11.0 / math.log10(0.9621))
    iters_needed_effective = math.ceil(-11.0 / math.log10(0.293))
    assert iters_needed_linear > 600
    assert iters_needed_effective < 30


def test_finding1_honest_fix_readme_states_effective_modulus():
    """Honest-fix: the README reports an effective modulus near 0.29 and
    reconciles it with the iteration count."""
    m = re.search(r"effective\s+modulus of about \$([0-9.]+)\$", README)
    assert m is not None, "effective modulus statement not found in README"
    assert abs(float(m.group(1)) - 0.293) < 0.05
    assert "linear-term" in README


# ---------------------------------------------------------------------------
# Finding 2: solver diagnostics must be persisted to a CSV artifact.
# ---------------------------------------------------------------------------
def test_finding2_violated_invariant_no_diagnostics_csv():
    """Violated invariant: no committed artifact holds the solver diagnostics.

    The buggy tutorial only emitted the two result CSVs. This test passes on
    the buggy repo and FAILS once tables/solver-diagnostics.csv is added.
    """
    assert not DIAGNOSTICS_CSV.exists()


def test_finding2_honest_fix_diagnostics_csv_exists():
    """Honest-fix: tables/solver-diagnostics.csv carries policy gap, grid gap,
    and iteration counts."""
    assert DIAGNOSTICS_CSV.exists()
    df = pd.read_csv(DIAGNOSTICS_CSV)
    for column in ("policy_gap_pct", "grid_gap_pct", "iterations"):
        assert column in df.columns


def test_finding2_readme_policy_gap_matches_csv():
    """The README policy gap matches the persisted CSV value."""
    df = pd.read_csv(DIAGNOSTICS_CSV)
    policy_gap = float(df["policy_gap_pct"].dropna().iloc[0])
    m = re.search(r"maximum policy gap[^*]*\*\*([0-9.]+)%\*\*", README)
    assert m is not None, "README policy gap claim not found"
    assert abs(float(m.group(1)) - policy_gap) < 0.01
