#!/usr/bin/env python3
"""Weak-form efficient-market diagnostics for yield changes."""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from lib.output import ModelReport
from lib.plotting import setup_style


def load_changes() -> pd.DataFrame:
    """Load ten-year Treasury yield changes from the static dataset."""
    path = Path(__file__).resolve().parents[1] / "_data" / "daily-treasury-rates.csv"
    df = pd.read_csv(path)
    df["Date"] = pd.to_datetime(df["Date"], format="%m/%d/%Y")
    df = df.sort_values("Date").reset_index(drop=True)
    df["dy"] = df["10 Yr"].diff()
    return df.dropna().reset_index(drop=True)


def autocorrelations(x: np.ndarray, max_lag: int = 20) -> pd.DataFrame:
    """Compute sample autocorrelations by lag."""
    rows = []
    centered = x - x.mean()
    denom = np.sum(centered**2)
    for lag in range(1, max_lag + 1):
        corr = float(np.sum(centered[lag:] * centered[:-lag]) / denom)
        rows.append({"Lag": lag, "Autocorrelation": corr})
    return pd.DataFrame(rows)


def variance_ratio(x: np.ndarray, q: int) -> float:
    """Compute the simple variance ratio for q-period changes."""
    overlapping = np.convolve(x, np.ones(q), mode="valid")
    return float(np.var(overlapping, ddof=1) / (q * np.var(x, ddof=1)))


def predictive_regression(x: np.ndarray) -> tuple[float, float, float]:
    """Estimate dy[t+1] = alpha + beta dy[t]."""
    y = x[1:]
    lag = x[:-1]
    design = np.column_stack([np.ones_like(lag), lag])
    alpha, beta = np.linalg.lstsq(design, y, rcond=None)[0]
    fitted = design @ np.array([alpha, beta])
    ssr = float(np.sum((y - fitted) ** 2))
    sst = float(np.sum((y - y.mean()) ** 2))
    return float(alpha), float(beta), 1.0 - ssr / sst


def diagnostic_table(changes: np.ndarray) -> pd.DataFrame:
    """Return weak-form diagnostic statistics."""
    alpha, beta, r2 = predictive_regression(changes)
    rows = [
        {"Diagnostic": "Mean daily change (bp)", "Value": f"{100.0 * changes.mean():.2f}", "Null benchmark": "0"},
        {"Diagnostic": "Lag-1 predictive slope", "Value": f"{beta:.3f}", "Null benchmark": "0"},
        {"Diagnostic": "Predictive R-squared", "Value": f"{r2:.3f}", "Null benchmark": "0"},
    ]
    for q in [2, 5, 10, 20]:
        rows.append(
            {
                "Diagnostic": f"Variance ratio q={q}",
                "Value": f"{variance_ratio(changes, q):.3f}",
                "Null benchmark": "1",
            }
        )
    rows.append({"Diagnostic": "Regression intercept (bp)", "Value": f"{100.0 * alpha:.2f}", "Null benchmark": "0"})
    return pd.DataFrame(rows)


def main() -> None:
    setup_style()
    df = load_changes()
    changes = df["dy"].to_numpy()
    acf = autocorrelations(changes)
    diagnostics = diagnostic_table(changes)
    r2_text = diagnostics.loc[diagnostics["Diagnostic"] == "Predictive R-squared", "Value"].iloc[0]

    print("Efficient-market diagnostics")
    print(diagnostics.to_string(index=False))

    report = ModelReport(
        "Weak-Form Efficiency in Treasury Yield Changes",
        "Autocorrelation, variance-ratio, and one-lag forecast checks for a static Treasury CMT sample.",
        include_reproduce=False,
        show_figure_captions=False,
    )

    report.add_overview(
        "Weak-form efficiency is a restriction on conditional predictability. Once the "
        "expected-return model is fixed, information already in past prices should not "
        "forecast the next excess return. With the offline data available here, the closest "
        "clean object is not a full bond return but the daily change in the ten-year "
        "Treasury constant-maturity yield.\n\n"
        "The tutorial should therefore be read as a random-walk diagnostic for yield "
        "changes, not as a trading strategy or a replication of CRSP-style return tests. "
        "The [Treasury yield-curve tutorial](../treasury-yield-curve/) explains the CMT "
        "data object; the [Fama-Bliss-style regression](../fama-bliss-forward-regression/) "
        "asks a more structured term-premium predictability question."
    )

    report.add_equations(
        r"""
Let $y_t$ be the annualized ten-year CMT yield in percent on date $t$, and
define the one-day change

$$
\Delta y_t = y_t - y_{t-1}.
$$

Let $\mathcal{F}^{p}_t$ denote the information generated by lagged yield
changes. The teaching null is

$$
\mathbb{E}\!\left[\Delta y_{t+1}-\mu \mid \mathcal{F}^{p}_t\right] = 0,
$$

where $\mu$ is the unconditional drift in daily yield changes. A one-lag
linear check estimates

$$
\Delta y_{t+1} = \alpha + \beta \Delta y_t + \epsilon_{t+1},
$$

with $\beta=0$ under the simple no-predictability benchmark.

The sample autocorrelation at lag $k$ is

$$
\hat{\rho}_k =
\frac{\sum_{t=k+1}^{T}(\Delta y_t-\overline{\Delta y})
(\Delta y_{t-k}-\overline{\Delta y})}
{\sum_{t=1}^{T}(\Delta y_t-\overline{\Delta y})^2}.
$$

For horizon $q$, define the overlapping $q$-day change

$$
\Delta_q y_t = y_t-y_{t-q}
= \sum_{h=0}^{q-1}\Delta y_{t-h}.
$$

The variance ratio is

$$
\widehat{VR}(q) =
\frac{\widehat{\operatorname{Var}}(\Delta_q y_t)}
{q\,\widehat{\operatorname{Var}}(\Delta y_t)}.
$$

Independent increments imply $\rho_k=0$ and $VR(q)=1$. A rejection of those
restrictions is still a joint statement about market efficiency, expected
returns, and measurement.
"""
    )

    report.add_model_setup(
        f"| Object | Value |\n"
        f"|--------|-------|\n"
        f"| Series | Daily 10-year Treasury CMT yield changes |\n"
        f"| Data | Static 1990 Treasury CMT snapshot |\n"
        f"| Date range for changes | {df['Date'].min().date()} to {df['Date'].max().date()} |\n"
        f"| Number of daily changes | {len(changes)} |\n"
        f"| Unit | Percentage-point changes; table reports basis points where stated |\n"
        f"| Autocorrelation lags | 1 to 20 |\n"
        f"| Variance-ratio horizons | 2, 5, 10, 20 days |\n"
        f"| Null reference | Random-walk increments with no lagged-price predictability |\n"
        f"| Interpretation | Weak-form diagnostic, not a bond-return backtest |"
    )

    report.add_solution_method(
        "The computation keeps the economic null visible. First form daily yield changes. "
        "Then ask three versions of the same question: do lagged changes forecast the next "
        "change, do autocorrelations drift away from zero, and does multi-day variance scale "
        "linearly with the horizon? The variance-ratio diagnostic follows the Lo-MacKinlay "
        "idea, but this tutorial reports the transparent ratio rather than the full "
        "heteroskedasticity-robust test statistic.\n\n"
        "```text\n"
        "Algorithm: weak-form diagnostics for Treasury yield changes\n"
        "Input: dates t, ten-year CMT yields y_t, lags K, horizons Q\n"
        "Output: autocorrelations, variance ratios, one-lag forecast regression, table\n"
        "Sort observations by date\n"
        "Form daily changes Delta y_t = y_t - y_{t-1}\n"
        "Compute the sample drift mean(Delta y_t)\n"
        "For each lag k = 1, ..., K:\n"
        "    compute the sample autocorrelation rho_hat_k\n"
        "For each horizon q in Q:\n"
        "    form overlapping q-day changes Delta_q y_t\n"
        "    compute VR_hat(q) = Var(Delta_q y_t) / (q Var(Delta y_t))\n"
        "Estimate Delta y_{t+1} = alpha + beta Delta y_t + epsilon_{t+1}\n"
        "Compare rho_hat_k with zero and VR_hat(q) with one\n"
        "Read deviations as random-walk diagnostics, not as arbitrage profits\n"
        "```\n\n"
        "The reference lines in the figures are the random-walk benchmarks: zero "
        "autocorrelation, a rough finite-sample band of $\pm 2/\sqrt{T}$, and a variance "
        "ratio of one. Those are the right ground-truth objects for this diagnostic "
        "exercise; adding a finer grid would not turn CMT yield changes into realized "
        "holding-period returns."
    )

    fig1, ax1 = plt.subplots(figsize=(7.4, 4.8))
    ax1.bar(acf["Lag"], acf["Autocorrelation"], color="tab:blue", label="Sample autocorrelation")
    ax1.axhline(0.0, color="black", linewidth=1.0, label="Zero")
    band = 2.0 / np.sqrt(len(changes))
    ax1.axhline(band, color="gray", linestyle="--", linewidth=1.0, label="Approx. 95% band")
    ax1.axhline(-band, color="gray", linestyle="--", linewidth=1.0)
    ax1.set_xlabel("Lag")
    ax1.set_ylabel("Autocorrelation")
    ax1.set_title("Autocorrelation of Yield Changes")
    ax1.legend(loc="upper right")
    report.add_figure(
        "figures/autocorrelations.png",
        "Autocorrelations of daily ten-year Treasury yield changes",
        fig1,
        description=(
            "The autocorrelation plot asks whether lagged yield changes contain useful "
            "forecast content. Most bars sit near zero. A few lags cross the rough "
            f"$\\pm 2/\\sqrt{{T}}$ band of **{band:.3f}**, which is enough to flag "
            "serial-dependence diagnostics but not enough, by itself, to establish an "
            "exploitable market inefficiency."
        ),
    )

    q_values = np.array([2, 5, 10, 20])
    vr_values = np.array([variance_ratio(changes, int(q)) for q in q_values])
    fig2, ax2 = plt.subplots(figsize=(7.0, 4.8))
    ax2.plot(q_values, vr_values, marker="o", linewidth=2.0, label="Sample variance ratio")
    ax2.axhline(1.0, color="black", linestyle="--", linewidth=1.0, label="Random-walk benchmark")
    ax2.set_xlabel("Horizon q")
    ax2.set_ylabel("Variance ratio")
    ax2.set_title("Variance-Ratio Diagnostics")
    ax2.legend(loc="upper right")
    report.add_figure(
        "figures/variance-ratios.png",
        "Variance ratios for yield changes",
        fig2,
        description=(
            "The variance-ratio plot puts the same issue in horizon form. The ratios are "
            f"above one at two and five days, with $VR(5)={vr_values[1]:.3f}$, then move "
            "closer to the random-walk benchmark at longer horizons. The pattern says that "
            "short-run yield changes in this 1990 snapshot are mildly persistent, not that "
            "the sample has uncovered a free trading rule."
        ),
    )

    report.add_table(
        "tables/efficient-market-diagnostics.csv",
        "Weak-form diagnostic summary",
        diagnostics,
        description=(
            "The table keeps the magnitudes auditable. The one-lag slope is positive but "
            f"small, with an $R^2$ of **{r2_text}**, about {100.0 * float(r2_text):.1f} "
            "percent of next-day variation. That is a different claim from saying prices "
            "are fully efficient or inefficient."
        ),
    )

    report.add_takeaway(
        "Weak-form tests are useful because they make the no-predictability restriction "
        "concrete. In this static CMT sample, daily ten-year yield changes show mild "
        "short-run persistence, but the economic interpretation remains narrow: the null "
        "bundles market efficiency with the expected-return model, the choice of yield "
        "changes rather than bond returns, and the finite 1990 sample."
    )
    report.add_references(
        [
            "[Fama, E. F. (1970). Efficient Capital Markets: A Review of Theory and Empirical Work. Journal of Finance, 25(2), 383-417.](https://doi.org/10.2307/2325486)",
            "[Lo, A. W., and MacKinlay, A. C. (1988). Stock Market Prices Do Not Follow Random Walks. Review of Financial Studies, 1, 41-66.](https://web.mit.edu/~alo/www/Papers/lo-mackinlay-88.html)",
        ]
    )
    report.write()


if __name__ == "__main__":
    main()
